"use client";

// ============================================================
// comparison/page.tsx — Solid / Honeycomb / Bone comparison
// ============================================================

import React, { useMemo, useState } from "react";
import { SimulationProvider, useSimulation } from "@/components/simulation/SimulationContext";
import { computeComparison } from "@/lib/simulation/comparison";
import { SliderControl } from "@/components/ui/SliderControl";
import type { ComparisonResult } from "@/lib/simulation/types";
import styles from "./comparison.module.css";

const MODEL_NAMES: Record<string, string> = {
  solid: "▪ Solid",
  honeycomb: "⬡ Honeycomb",
  bone: "⁜ Bone-Inspired",
};

const MODEL_COLORS: Record<string, string> = {
  solid: "#86CFF5",
  honeycomb: "#4EA9E0",
  bone: "#F2C94C",
};

const METRICS: Array<{
  key: keyof ComparisonResult;
  label: string;
  unit?: string;
  higherIsBetter?: boolean;
}> = [
  { key: "relativeDensity", label: "Relative Density", higherIsBetter: false },
  { key: "porosity", label: "Porosity", higherIsBetter: true },
  { key: "materialFraction", label: "Material Fraction", higherIsBetter: false },
  { key: "stressIndex", label: "Stress Index", unit: "/100", higherIsBetter: false },
  { key: "deformation", label: "Deformation", unit: " su", higherIsBetter: false },
  { key: "estimatedMassG", label: "Est. Mass", unit: " g", higherIsBetter: false },
  { key: "effectiveStiffness", label: "Eff. Stiffness", higherIsBetter: true },
];

function BarChart({
  results,
  metricKey,
  unit,
}: {
  results: ComparisonResult[];
  metricKey: keyof ComparisonResult;
  unit?: string;
}) {
  const values = results.map((r) => Number(r[metricKey]));
  const maxVal = Math.max(...values, 0.001);

  return (
    <div className={styles.barChart}>
      {results.map((r, i) => {
        const val = Number(r[metricKey]);
        const pct = (val / maxVal) * 100;
        return (
          <div key={r.modelType} className={styles.barRow}>
            <span className={styles.barLabel}>{MODEL_NAMES[r.modelType]}</span>
            <div className={styles.barTrack}>
              <div
                className={styles.barFill}
                style={{
                  width: `${pct}%`,
                  background: MODEL_COLORS[r.modelType],
                }}
              />
            </div>
            <span className={styles.barValue} style={{ color: MODEL_COLORS[r.modelType] }}>
              {isFinite(val) ? val.toFixed(val > 10 ? 1 : 3) : "—"}
              {unit}
            </span>
          </div>
        );
      })}
    </div>
  );
}

function ComparisonContent() {
  const { state, setParam } = useSimulation();

  const results = useMemo(() => computeComparison(state), [state]);

  return (
    <div className="container section">
      <div className="section-title">
        <h2>Structural Strategy Comparison</h2>
      </div>

      <p className={styles.intro}>
        All three structural strategies are evaluated under the{" "}
        <span style={{ color: "#F2C94C" }}>same applied load</span>. Metrics are
        generated by the simulation engine — not pre-defined.
      </p>

      {/* ── Load control ───────────────────────────────────── */}
      <div className={`card ${styles.loadControl}`}>
        <div style={{ display: "flex", alignItems: "center", gap: "1rem", flexWrap: "wrap" }}>
          <span style={{ color: "#A9BCD2", fontSize: "0.8rem", fontWeight: 600, minWidth: 100 }}>
            Applied Load:
          </span>
          <div style={{ flex: 1, minWidth: 200 }}>
            <SliderControl
              label="Load"
              value={state.loadN}
              min={500}
              max={3000}
              step={50}
              unit=" N"
              accentColor="yellow"
              onChange={(v) => setParam("loadN", v)}
            />
          </div>
          <span style={{ color: "#F2C94C", fontWeight: 800, fontSize: "1.2rem" }}>
            {state.loadN} N
          </span>
        </div>
      </div>

      {/* ── Summary table ──────────────────────────────────── */}
      <div className={styles.tableWrap}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Metric</th>
              {results.map((r) => (
                <th key={r.modelType} style={{ color: MODEL_COLORS[r.modelType] }}>
                  {MODEL_NAMES[r.modelType]}
                </th>
              ))}
              <th>Best</th>
            </tr>
          </thead>
          <tbody>
            {METRICS.map(({ key, label, unit, higherIsBetter }) => {
              const values = results.map((r) => Number(r[key]));
              const bestVal = higherIsBetter
                ? Math.max(...values)
                : Math.min(...values);

              return (
                <tr key={key}>
                  <td className={styles.metricName}>{label}</td>
                  {results.map((r) => {
                    const val = Number(r[key]);
                    const isBest = Math.abs(val - bestVal) < 0.001;
                    return (
                      <td
                        key={r.modelType}
                        className={`${styles.metricVal} ${isBest ? styles.best : ""}`}
                        style={isBest ? { color: MODEL_COLORS[r.modelType] } : {}}
                      >
                        {isFinite(val) ? val.toFixed(val > 10 ? 1 : 3) : "—"}
                        {unit}
                      </td>
                    );
                  })}
                  <td className={styles.bestBadge}>
                    {results.find((r) => {
                      const val = Number(r[key]);
                      return Math.abs(val - bestVal) < 0.001;
                    }) && (
                      <span
                        className="badge"
                        style={{
                          background: `rgba(${
                            MODEL_COLORS[
                              results.find((r) => Math.abs(Number(r[key]) - bestVal) < 0.001)!.modelType
                            ] === "#F2C94C"
                              ? "242,201,76"
                              : "78,169,224"
                          },0.15)`,
                          color: MODEL_COLORS[
                            results.find((r) => Math.abs(Number(r[key]) - bestVal) < 0.001)!.modelType
                          ],
                          border: "none",
                          fontSize: "0.65rem",
                        }}
                      >
                        {
                          MODEL_NAMES[
                            results.find((r) => Math.abs(Number(r[key]) - bestVal) < 0.001)!.modelType
                          ]
                        }
                      </span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ── Bar charts ─────────────────────────────────────── */}
      <div className="grid-3" style={{ marginTop: "2rem" }}>
        {METRICS.slice(0, 6).map(({ key, label, unit }) => (
          <div key={key} className="card">
            <h4
              style={{
                color: "#A9BCD2",
                fontSize: "0.75rem",
                textTransform: "uppercase",
                letterSpacing: "0.08em",
                marginBottom: "0.75rem",
              }}
            >
              {label}
            </h4>
            <BarChart results={results} metricKey={key} unit={unit} />
          </div>
        ))}
      </div>

      {/* ── Experimental reference ─────────────────────────── */}
      <div className={`card ${styles.expCard}`} style={{ marginTop: "2rem" }}>
        <div className={styles.expHeader}>
          <span className="badge badge-yellow">📄 Experimental Reference</span>
          <span style={{ color: "#6A8BA8", fontSize: "0.75rem" }}>
            Naboni R. & Kunic A. (2019)
          </span>
        </div>
        <h3 style={{ color: "#F4F8FC", margin: "0.75rem 0 0.5rem", fontSize: "1.05rem" }}>
          Bone-Inspired 3D Printed Structures for Construction Applications
        </h3>
        <div className="grid-3" style={{ marginTop: "1rem" }}>
          {[
            { label: "Lattice Brick Mass", value: "185 g", note: "Measured" },
            { label: "Compression Resistance", value: "up to 3000 N", note: "Measured" },
            { label: "Load-to-Weight Ratio", value: "~1600×", note: "Reported" },
          ].map((item) => (
            <div key={item.label} style={{ textAlign: "center" }}>
              <div style={{ fontSize: "1.6rem", fontWeight: 800, color: "#F2C94C", letterSpacing: "-0.02em" }}>
                {item.value}
              </div>
              <div style={{ fontSize: "0.72rem", color: "#A9BCD2", marginTop: "0.2rem" }}>
                {item.label}
              </div>
              <div style={{ fontSize: "0.65rem", color: "#6A8BA8" }}>{item.note}</div>
            </div>
          ))}
        </div>
        <div className="disclaimer" style={{ marginTop: "1rem" }}>
          These are <strong>source experimental values</strong> from Naboni & Kunic (2019).
          They are NOT used as hidden calibration constants. Browser simulation values are
          generated independently and shown separately.
        </div>
      </div>

      {/* ── Browser sim values ─────────────────────────────── */}
      <div className={`card ${styles.simCard}`} style={{ marginTop: "1.25rem" }}>
        <div className={styles.expHeader}>
          <span className="badge badge-blue">💻 Conceptual Browser Simulation</span>
          <span style={{ color: "#6A8BA8", fontSize: "0.75rem" }}>Generated by engine</span>
        </div>
        <div className="grid-3" style={{ marginTop: "1rem" }}>
          {results.map((r) => (
            <div key={r.modelType} className="card" style={{ background: "#071A36" }}>
              <div style={{ color: MODEL_COLORS[r.modelType], fontWeight: 700, marginBottom: "0.5rem", fontSize: "0.9rem" }}>
                {MODEL_NAMES[r.modelType]}
              </div>
              <div style={{ fontSize: "0.78rem", color: "#A9BCD2", lineHeight: 1.8 }}>
                <div>Mass: <span style={{ color: "#F4F8FC" }}>{r.estimatedMassG.toFixed(1)} g</span></div>
                <div>Stress Index: <span style={{ color: "#F4F8FC" }}>{r.stressIndex.toFixed(1)} /100</span></div>
                <div>Deformation: <span style={{ color: "#F4F8FC" }}>{r.deformation.toFixed(4)} su</span></div>
                <div>Eff. Stiffness: <span style={{ color: "#F4F8FC" }}>{r.effectiveStiffness.toFixed(4)}</span></div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default function ComparisonPage() {
  return (
    <SimulationProvider>
      <ComparisonContent />
    </SimulationProvider>
  );
}
