"use client";

// ============================================================
// comparison/page.tsx — Solid / Honeycomb / Bone comparison
// ============================================================

import React, { useMemo } from "react";
import { SimulationProvider, useSimulation } from "@/components/simulation/SimulationContext";
import { computeComparison } from "@/lib/simulation/comparison";
import { SliderControl } from "@/components/ui/SliderControl";
import type { ComparisonResult } from "@/lib/simulation/types";
import { LOAD_MIN_N, LOAD_MAX_N } from "@/lib/simulation/constants";
import styles from "./comparison.module.css";

const MODEL_NAMES: Record<string, string> = {
  solid: "▪ Solid (Brick)",
  honeycomb: "⬡ Honeycomb",
  bone: "⁜ Bone-Inspired",
};

const MODEL_COLORS: Record<string, string> = {
  solid: "#3A88C8",
  honeycomb: "#D4A017",
  bone: "#2E9B66",
};

const MODEL_BG_ACCENTS: Record<string, string> = {
  solid: "#DCEFFA",
  honeycomb: "#FFF5CF",
  bone: "#E5F6ED",
};

const METRICS: Array<{
  key: keyof ComparisonResult;
  label: string;
  unit?: string;
  higherIsBetter?: boolean;
}> = [
  { key: "relativeDensity", label: "Relative Density", higherIsBetter: false },
  { key: "porosity", label: "Porosity", higherIsBetter: true },
  { key: "materialFraction", label: "Material Fraction", higherIsBetter: false },
  { key: "stressIndex", label: "Stress Index", unit: "/100", higherIsBetter: false },
  { key: "deformation", label: "Deformation", unit: " su", higherIsBetter: false },
  { key: "estimatedMassG", label: "Est. Mass", unit: " g", higherIsBetter: false },
  { key: "effectiveStiffness", label: "Eff. Stiffness", higherIsBetter: true },
  { key: "failureThresholdN", label: "Failure Threshold", unit: " N", higherIsBetter: true },
];

function BarChart({
  results,
  metricKey,
  unit,
}: {
  results: ComparisonResult[];
  metricKey: keyof ComparisonResult;
  unit?: string;
}) {
  const values = results.map((r) => Number(r[metricKey]));
  const maxVal = Math.max(...values, 0.001);

  return (
    <div className={styles.barChart}>
      {results.map((r) => {
        const val = Number(r[metricKey]);
        const pct = (val / maxVal) * 100;
        return (
          <div key={r.modelType} className={styles.barRow}>
            <span className={styles.barLabel}>{MODEL_NAMES[r.modelType]}</span>
            <div className={styles.barTrack}>
              <div
                className={styles.barFill}
                style={{
                  width: `${pct}%`,
                  background: MODEL_COLORS[r.modelType],
                }}
              />
            </div>
            <span className={styles.barValue} style={{ color: MODEL_COLORS[r.modelType] }}>
              {isFinite(val) ? val.toFixed(val > 10 ? 0 : 3) : "—"}
              {unit}
            </span>
          </div>
        );
      })}
    </div>
  );
}

function ComparisonContent() {
  const { state, setParam } = useSimulation();

  const results = useMemo(() => computeComparison(state), [state]);

  return (
    <div className="container section">
      <div className="section-title">
        <h2>Structural Strategy Comparison</h2>
      </div>

      <p className={styles.intro}>
        All three structural strategies are evaluated under the{" "}
        <span style={{ color: "#D4A017", fontWeight: 700 }}>same applied load</span>. Metrics are
        generated by the simulation engine — not hard-coded.
      </p>

      {/* ── Load control ───────────────────────────────────── */}
      <div className={`card ${styles.loadControl}`}>
        <div style={{ display: "flex", alignItems: "center", gap: "1.25rem", flexWrap: "wrap" }}>
          <span style={{ color: "#243447", fontSize: "0.85rem", fontWeight: 700, minWidth: 100 }}>
            Applied Load:
          </span>
          <div style={{ flex: 1, minWidth: 220 }}>
            <SliderControl
              label="Load Force"
              value={state.loadN}
              min={LOAD_MIN_N}
              max={LOAD_MAX_N}
              step={50}
              unit=" N"
              accentColor="yellow"
              onChange={(v) => setParam("loadN", v)}
            />
          </div>
          <span style={{ color: "#D4A017", fontWeight: 800, fontSize: "1.3rem" }}>
            {state.loadN} N
          </span>
        </div>
      </div>

      {/* ── Summary table ──────────────────────────────────── */}
      <div className={styles.tableWrap}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Metric</th>
              {results.map((r) => (
                <th key={r.modelType} style={{ color: MODEL_COLORS[r.modelType] }}>
                  {MODEL_NAMES[r.modelType]}
                </th>
              ))}
              <th>Best Efficiency</th>
            </tr>
          </thead>
          <tbody>
            {METRICS.map(({ key, label, unit, higherIsBetter }) => {
              const values = results.map((r) => Number(r[key]));
              const bestVal = higherIsBetter
                ? Math.max(...values)
                : Math.min(...values);

              return (
                <tr key={key}>
                  <td className={styles.metricName}>{label}</td>
                  {results.map((r) => {
                    const val = Number(r[key]);
                    const isBest = Math.abs(val - bestVal) < 0.001;
                    return (
                      <td
                        key={r.modelType}
                        className={`${styles.metricVal} ${isBest ? styles.best : ""}`}
                        style={isBest ? { color: MODEL_COLORS[r.modelType] } : {}}
                      >
                        {isFinite(val) ? val.toFixed(val > 10 ? (val > 100 ? 0 : 1) : 3) : "—"}
                        {unit}
                      </td>
                    );
                  })}
                  <td className={styles.bestBadge}>
                    {results.find((r) => {
                      const val = Number(r[key]);
                      return Math.abs(val - bestVal) < 0.001;
                    }) && (
                      <span
                        className="badge"
                        style={{
                          background:
                            MODEL_BG_ACCENTS[
                              results.find((r) => Math.abs(Number(r[key]) - bestVal) < 0.001)!.modelType
                            ],
                          color:
                            MODEL_COLORS[
                              results.find((r) => Math.abs(Number(r[key]) - bestVal) < 0.001)!.modelType
                            ],
                          border: `1px solid ${
                            MODEL_COLORS[
                              results.find((r) => Math.abs(Number(r[key]) - bestVal) < 0.001)!.modelType
                            ]
                          }`,
                          fontSize: "0.68rem",
                        }}
                      >
                        {
                          MODEL_NAMES[
                            results.find((r) => Math.abs(Number(r[key]) - bestVal) < 0.001)!.modelType
                          ]
                        }
                      </span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ── Bar charts ─────────────────────────────────────── */}
      <div className="grid-3" style={{ marginTop: "2rem" }}>
        {METRICS.slice(0, 6).map(({ key, label, unit }) => (
          <div key={key} className="card">
            <h4
              style={{
                color: "#62748A",
                fontSize: "0.75rem",
                textTransform: "uppercase",
                letterSpacing: "0.08em",
                marginBottom: "0.85rem",
              }}
            >
              {label}
            </h4>
            <BarChart results={results} metricKey={key} unit={unit} />
          </div>
        ))}
      </div>

      {/* ── Experimental reference ─────────────────────────── */}
      <div className={`card ${styles.expCard}`} style={{ marginTop: "2rem" }}>
        <div className={styles.expHeader}>
          <span className="badge badge-yellow">📄 Experimental Reference Benchmark</span>
          <span style={{ color: "#62748A", fontSize: "0.75rem" }}>
            Roberto Naboni &amp; Anja Kunic (2019)
          </span>
        </div>
        <h3 style={{ color: "#243447", margin: "0.75rem 0 0.5rem", fontSize: "1.15rem" }}>
          Bone-Inspired 3D Printed Structures for Construction Applications
        </h3>
        <div className="grid-3" style={{ marginTop: "1rem" }}>
          {[
            { label: "Lattice Brick Mass", value: "185 g", note: "Measured test piece" },
            { label: "Compression Resistance", value: "up to 3000 N", note: "Peak measured load" },
            { label: "Load-to-Weight Ratio", value: "~1600×", note: "Reported efficiency" },
          ].map((item) => (
            <div key={item.label} className={styles.statBox}>
              <div style={{ fontSize: "1.6rem", fontWeight: 800, color: "#D4A017", letterSpacing: "-0.02em" }}>
                {item.value}
              </div>
              <div style={{ fontSize: "0.75rem", fontWeight: 600, color: "#243447", marginTop: "0.25rem" }}>
                {item.label}
              </div>
              <div style={{ fontSize: "0.68rem", color: "#62748A" }}>{item.note}</div>
            </div>
          ))}
        </div>
        <div className="disclaimer" style={{ marginTop: "1.25rem" }}>
          These are <strong>source experimental values</strong> from Naboni &amp; Kunic (2019).
          They are NOT used as hidden calibration constants. Browser simulation values are
          generated independently and shown separately below.
        </div>
      </div>

      {/* ── Browser sim values ─────────────────────────────── */}
      <div className={`card ${styles.simCard}`} style={{ marginTop: "1.25rem" }}>
        <div className={styles.expHeader}>
          <span className="badge badge-blue">💻 Conceptual Browser Simulation</span>
          <span style={{ color: "#62748A", fontSize: "0.75rem" }}>Generated live by mathematical engine</span>
        </div>
        <div className="grid-3" style={{ marginTop: "1rem" }}>
          {results.map((r) => (
            <div
              key={r.modelType}
              className="card"
              style={{
                background: "#FFFFFF",
                borderTop: `4px solid ${MODEL_COLORS[r.modelType]}`,
              }}
            >
              <div style={{ color: MODEL_COLORS[r.modelType], fontWeight: 700, marginBottom: "0.6rem", fontSize: "0.95rem" }}>
                {MODEL_NAMES[r.modelType]}
              </div>
              <div style={{ fontSize: "0.82rem", color: "#62748A", lineHeight: 1.85 }}>
                <div>Mass Estimate: <strong style={{ color: "#243447" }}>{r.estimatedMassG.toFixed(1)} g</strong></div>
                <div>Stress Index: <strong style={{ color: "#243447" }}>{r.stressIndex.toFixed(1)} /100</strong></div>
                <div>Deformation: <strong style={{ color: "#243447" }}>{r.deformation.toFixed(4)} su</strong></div>
                <div>Eff. Stiffness: <strong style={{ color: "#243447" }}>{r.effectiveStiffness.toFixed(4)}</strong></div>
                <div>Threshold: <strong style={{ color: r.isFailed ? "#D9534F" : "#243447" }}>{r.failureThresholdN} N {r.isFailed ? "(EXCEEDED)" : "(INTACT)"}</strong></div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default function ComparisonPage() {
  return (
    <SimulationProvider>
      <ComparisonContent />
    </SimulationProvider>
  );
}
