// ============================================================
// comparison.ts — Solid / Honeycomb / Bone-Inspired comparison
// ============================================================
// All values are generated by the simulation engine using the
// same applied load. No values are hard-coded.
// ============================================================

import type { SimulationState, ComparisonResult } from "./types";
import { clamp, safeNumber } from "./normalize";
import { computeNormalizedLoad } from "./loadModel";
import { computeStressIndex, computeRelativeStiffness } from "./stressModel";
import { computeDeformation } from "./deformationModel";
import {
  computeHoneycombRelativeDensity,
  computeHoneycombPorosity,
  computeHoneycombSolidVolume,
  generateHoneycombCells,
} from "./honeycombModel";
import {
  generateStrutNetwork,
  computeAverageRelativeDensity,
  computeAverageOrientationFactor,
  computeStrutNetworkVolume,
  computeBoneRelativeStiffness,
  computeOrientationFactor,
} from "./boneInspiredModel";
import {
  estimateMassGrams,
  estimateSolidVolumeFromDensity,
} from "./materialModel";
import { MATERIAL_PA12, BOUNDING_VOLUME_M3 } from "./constants";
import { MIN_ORIENTATION_FACTOR } from "./constants";

/**
 * Compute comparison metrics for all three structural strategies
 * using the SAME applied load from the simulation state.
 */
export function computeComparison(state: SimulationState): ComparisonResult[] {
  const { loadN, cellSizeMm, wallThicknessMm, cellCount, orientationDeg } = state;

  // ─── SOLID ──────────────────────────────────────────────────
  const solidRho = 1.0;
  const solidPorosity = 0.0;
  const solidStressIndex = computeStressIndex(loadN, solidRho, 1.0);
  const solidDeformation = computeDeformation(loadN, solidRho, 1.0, 1.0);
  const solidVolume = BOUNDING_VOLUME_M3;
  const solidMass = estimateMassGrams(solidVolume, MATERIAL_PA12.density);
  const solidStiffness = computeRelativeStiffness(solidRho);

  const solidResult: ComparisonResult = {
    modelType: "solid",
    relativeDensity: solidRho,
    porosity: solidPorosity,
    materialFraction: solidRho,
    stressIndex: safeNumber(solidStressIndex, 0),
    deformation: safeNumber(solidDeformation, 0),
    estimatedMassG: safeNumber(solidMass, 0),
    effectiveStiffness: safeNumber(solidStiffness, 1),
  };

  // ─── HONEYCOMB ──────────────────────────────────────────────
  const hcRho = computeHoneycombRelativeDensity(wallThicknessMm, cellSizeMm);
  const hcPorosity = computeHoneycombPorosity(hcRho);
  const hcStressIndex = computeStressIndex(loadN, hcRho, 0.85);
  const hcDeformation = computeDeformation(loadN, hcRho, 1.0, 0.85);
  const hcCells = generateHoneycombCells(cellSizeMm, wallThicknessMm, cellCount, loadN);
  const hcSolidVol = computeHoneycombSolidVolume(hcCells, wallThicknessMm, cellSizeMm);
  const hcMass = estimateMassGrams(hcSolidVol, MATERIAL_PA12.density);
  const hcStiffness = computeRelativeStiffness(hcRho);

  const honeycombResult: ComparisonResult = {
    modelType: "honeycomb",
    relativeDensity: hcRho,
    porosity: hcPorosity,
    materialFraction: hcRho,
    stressIndex: safeNumber(hcStressIndex, 0),
    deformation: safeNumber(hcDeformation, 0),
    estimatedMassG: safeNumber(hcMass, 0),
    effectiveStiffness: safeNumber(hcStiffness, 0),
  };

  // ─── BONE-INSPIRED ──────────────────────────────────────────
  const rho_base = clamp(state.relativeDensity, 0.15, 0.75);
  const struts = generateStrutNetwork(
    cellSizeMm,
    cellCount,
    loadN,
    orientationDeg,
    rho_base,
    42
  );
  const boneAvgRho = computeAverageRelativeDensity(struts);
  const bonePorosity = clamp(1 - boneAvgRho, 0, 1);
  const boneAvgOriFactor = computeAverageOrientationFactor(struts);
  const boneStiffness = computeBoneRelativeStiffness(boneAvgRho, boneAvgOriFactor);
  const boneStressIndex = computeStressIndex(loadN, boneAvgRho, boneAvgOriFactor);
  const boneDeformation = computeDeformation(
    loadN,
    boneAvgRho,
    1.0,
    boneAvgOriFactor
  );
  const boneSolidVol = computeStrutNetworkVolume(struts);
  const boneMass = estimateMassGrams(boneSolidVol, MATERIAL_PA12.density);

  const boneResult: ComparisonResult = {
    modelType: "bone",
    relativeDensity: boneAvgRho,
    porosity: bonePorosity,
    materialFraction: boneAvgRho,
    stressIndex: safeNumber(boneStressIndex, 0),
    deformation: safeNumber(boneDeformation, 0),
    estimatedMassG: safeNumber(boneMass, 0),
    effectiveStiffness: safeNumber(boneStiffness, 0),
  };

  return [solidResult, honeycombResult, boneResult];
}
